### PR TITLE
ESM and CJS Builds and upgrades to prosemirror

### PR DESCRIPTION
**Pull request by rowanc1**
There have been some major changes in the prosemirror ecosystem with type upgrades, etc. This is aimed to address:

- #16

I have released this as `0.4.0-rc.0`. Could @rfgamaral or @benkroeger give this a try in their apps to confirm the fix? Then I will release the minor version update.

### CODE REVIEW

**Comment by rowanc1** [comment]
Have confirmed this works as expected in the demo, and install works for our cjs deps in `@curvenote/editor` and types, etc.! (even though we have not upgraded to prosemirror there yet)

As I am working on this now, I am going to release this as 0.4.0, and if there are challenges with the ESM build or newer versions of tiptap, we can deal with them as patch releases there.

**Comment by rowanc1** [comment]
Should now be live as 0.4.0.

**Comment by rfgamaral** [comment]
This seems to have fixed the issue for us, thanks @rowanc1 🙏

**Comment by rowanc1** [comment]
Awesome, glad it's working! Thanks for reporting the issue!

**Comment by rowanc1** [comment]
This has resolved this issue: https://github.com/ueberdosis/tiptap/issues/2836

**Pull request merged**
